// Generated by LiveScript 1.5.0
/**
 * @package Ronion
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  var gulp;
  gulp = require('gulp');
  require('build-gbu')('src/index.js', 'ronion', 'ronion.browser', [], gulp);
  require('build-gc')('dist/ronion.browser.js', 'dist/ronion.browser.min.js', 'src/externs.js', {
    task: function(task, func){
      gulp.task(task, ['browserify'], func);
    }
  });
}).call(this);
