// Generated by LiveScript 1.5.0
/**
 * @package   Ronion
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2017, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  /**
   * @record
   */
  function Connection(){}
  /**
   * @type {Uint8Array} Fixed-size address of remote peer, can be anything: IP:port, ID, etc.
   */
  Connection.prototype.address;
  /**
   * Used in `data` event
   *
   * @callback ondata
   * @param {Uint8Array} data
   */
  /**
   * Add an event handler
   *
   * @param {string}				event		Either `data` or `close`
   * @param {(ondata|Function)}	callback
   *
   * @return {Connection}
   */
  Connection.prototype.on = function(event, callback){};
  /**
   * Remove event handler
   *
   * @param {string}		event		Either `data` or `close`
   * @param {Function}	callback
   *
   * @return {Connection}
   */
  Connection.prototype.off = function(event, callback){};
  /**
   * @param {Uint8Array} data
   */
  Connection.prototype.send = function(data){};
  Connection.prototype.close = function(){};
}).call(this);
